### ISSUE TITLE
BASIC text not pasting or importing

### ISSUE THREAD

**Issue by fluffymormegil** [commanderx16/x16-emulator#214] opened 2019-11-20 22:59 UTC
Running a locally compiled build of x16-emulator c8ec1b9f on a Debian buster system, with a locally built image of x16-rom 0772b9f3, I ran into the following misbehaviour.

When I use the -bas <file> command-line argument to fetch a text file as untokenized BASIC text, or use Ctrl-V in the running emulator to paste untokenized BASIC text:

1. No text is pasted into the emulated system.
2. The emulated system enters a state where the ROM sees some modifier key or other as permanently pressed, so that typing e.g. ASDF gets me box-drawing characters instead of letters.
3. The only way to recover the emulated system to a working state appears to be use Ctrl-R to reset the emulation.

**Comment by mist64** [comment] 2019-11-20 23:12
This is caused by a mismatch of some ROM symbols and emulator's idea of them. Fixed in 70e0d9f.

**Closed by mist64** 2019-11-20 23:12 UTC
