### ISSUE TITLE
Support non-US keyboards

### ISSUE THREAD

**Issue by rsbohn12** [commanderx16/x16-emulator#6] opened 2019-09-03 19:00 UTC
Can't type <<">> on the Norwegian, German, etc keyboard.
Maybe provide different key map based on the user's selected locale.

**Comment by fu-sen** [comment] 2019-09-05 02:30
Japanese keyboard does not seem to be able to input **=**,
**"** Is also included in the Japanese keyboard.

**Comment by paulscottrobson** [comment] 2019-09-05 22:34
It should, in theory, work if you press the same physical key as on a US keyboard (2 in from the bottom half of the ENTER key). I think what is happening is SDL is trying to be helpful, when what we actually want to do is to get the scan keys and send them straight back out again. 

Reading this https://wiki.libsdl.org/CategoryKeyboard it sounds like SDLs keycodes are modified using the modifiers (Shift, Ctrl, etc.) which would explain why SDLK_QUOTE and SDLK_QUOTEDBL both exist even though on a US keyboard it's the same key. 

This would explain why video.c maps both SDLK_QUOTE and SDLK_QUOTEDBL to the same scancode. 

If we were to use scancodes not SDL's keycodes then it would correlate to the physical location of the keys on the keyboards. This would make it irritating, but should mean the equivalent German key (a umlout ?) should work.

**Comment by paulscottrobson** [comment] 2019-09-06 10:14
Fixed to use Scancodes. Seems to work. Have requested assistance on FB for testing.

**Comment by mist64** [comment] 2019-09-06 11:32
Seems to work well. I merged it into my repo already. :)
3ebf94d962eacd023408fdbea3797b6105bd5708 & 9901ed675015ad73f6d884e7039d88a20e0ae106

**Comment by sebastianvog** [comment] 2019-09-06 17:04
If i switch to german keyboard layout i don't see much different behavior. so pressing SHIFT 2 still gives me a '@' instead of a ' " ' ? I am not sure if we intended to fix that or always assume a U.S. layout.

**Comment by mist64** [comment] 2019-09-06 17:06
It's always a US layout. The KERNAL ROM assumes an ANSI/US PS/2 keyboard, and that's how it translates scancodes to ASCII (PETSCII) characters. The KERNAL will gain support for other keyboard mappings in the future, but for now, that's what it is.

**Comment by sebastianvog** [comment] 2019-09-06 17:06
Ok, sounds good. thanks for explanation!

**Closed** 2019-09-06 19:35 UTC

**Comment by fu-sen** [comment] 2019-09-07 02:41
r29 allows you to input specific symbols,
but instead, there is a mismatch between the keyboard layout and the actual input.
I or you may reopen or new issue about this.

**Comment by sebastianvog** [comment] 2019-09-07 16:00
imho, it worked a bit better for international keyboards before it was switched to scan codes.
Reason being that the sdl key codes were at least partially layout aware. e.g. when set to a german keyboard layout a "y"  would come across correctly. with the scan codes we will send down a 'z'.  ( note: this didn't work for character pressed with shift like shift-" )

I still think though, the right solution is that we have to wait, as Michael says, until the kernal supports different key mappings. Having said that, I do work on a somewhat  dirty workaround to convert the scan code again, by listening to SDL_TEXTINPUT and then massaging the physical scancodes. Works great for a-z letters, but not yet for SHIFT-letters

**Comment by paulscottrobson** [comment] 2019-09-08 20:25
Yes, that's true. SDL tries to be helpful. The problem is that it doesn't replicate the hardware it's emulating, and on some keyboard layouts some keys are unobtainium. It will be fixed (probably)

**Comment by mobluse** [comment] 2019-09-10 15:39
These might be useful, but they use Alt on many places where the real C64 and X16 use Shift. In X16 Alt seems to work as the CBM key. 
https://retrogames.biz/thec64-mini/keyboard

This is also useful for finding which key one should press to get a certain character:
https://style64.org/petscii/
