### ISSUE TITLE
VPEEK command in BASIC

### ISSUE THREAD

**Issue by Pandamad** [commanderx16/x16-emulator#21] opened 2019-09-06 12:56 UTC
It is valid systax to type something like 

`?PEEK(1024+1)`

I can't do the same with VPEEK

`?VPEEK(4,10+1) `

gives a SYSTAX ERROR

**Comment by mist64** [comment] 2019-09-06 13:37
Reproduced.

**Comment by paulscottrobson** [comment] 2019-09-06 17:01
The tokenising is broken. ?VPEEK(10+1) has the same problem. It tokenises '+' as $2B, the ASCII value, not $AA, the token for '+'. So in the precedence climber, after parsing the 10 it finds a character when it's expecting an operator token (in FRMEVL), so it gives a Syntax error.

This does not happen with VPOKE, VPOKE 2,2+3,12 tokenises properly.

**Comment by paulscottrobson** [comment] 2019-09-06 17:22
IMO the reason is that when you tokenise VPEEK( it comes out as $CE83. Your code puts the $CE in manually and loops back to crdone0, which writes the token ($83) out and reads it back. It then tests for DATA. This token is DATA ($83) so it sets DATAFLG because it's the same token as a Data Statement ($83).

Might be best if you fix this one ? Options include a duplicate token (could put MON in there as an effective NOP, but this would muck up any programs already tokenised), or swap them round (as it doesn't matter for DOS/MON), or at the end of the write out, duplicate the code from crdone0 (most of the tests being irrelevant as we know the token is $80+) and then branching to colis.

**Comment by mist64** [comment] 2019-09-06 18:46
Thanks! I ended up just duplicating the store instruction.

Fixed in https://github.com/commanderx16/x16-rom/commit/131c1648277ed57657173d837180535542c69b86

**Closed by mist64** 2019-09-06 18:46 UTC
